spring:
  application:
    name: hong-eureka-provider-client
server:
  port: 6002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

